# Generated by Django 5.1.7 on 2025-03-14 09:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.UUID('303b517a-80c7-43da-95ec-3b6c3ed51817'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(85)])),
                ('blood_group', models.CharField(max_length=5)),
                ('medical_issue', models.CharField(max_length=30)),
                ('medication', models.CharField(max_length=30)),
                ('recent_bill', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2500)])),
                ('assigned_doctor', models.CharField(max_length=30)),
                ('last_visited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
